In [91]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
import torch.nn.functional as F
from torchvision.transforms import ToTensor
import numpy as np
import torch.onnx 
import torchvision
# from sklearn.model_selection import train_test_split
%matplotlib inline
from mycnn_lib import *
input_img_sz=12
# Download training data from open datasets.
training_data = datasets.MNIST(
    root="../../../data",    
    train=True,
    download=True,
    transform=torchvision.transforms.Compose(
    [torchvision.transforms.Resize(input_img_sz), torchvision.transforms.ToTensor()]
    ),
)

# Download test data from open datasets.
test_data = datasets.MNIST(
    root="../../../data",
    train=False,
    download=True,
    transform=torchvision.transforms.Compose(
        [torchvision.transforms.Resize(input_img_sz), torchvision.transforms.ToTensor()]
    ),
)

In [92]:
import TCB
def D2reg(num,reg_name):
    if(num==0):
        return None
    else:
        tcb_str=TCB.Bin2TCB(int(num))
        temp=0
        if(num>0):
            out_s="+(0"
        else:
            out_s="-(0"
        for s in reversed(tcb_str):
            if(s=="+"):
                out_s+="+("+reg_name+"<<"+str(temp)+")"
            if(s=="-"):
                out_s+="-("+reg_name+"<<"+str(temp)+")"
            temp+=1         
            
        return out_s+")"
D2reg(-29,"reg")        


'-(0+(reg<<0)-(reg<<2)+(reg<<5))'

In [93]:
# Get cpu or gpu device for training.
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

convolution_kernel_size =3
fc1_size=((input_img_sz- convolution_kernel_size+1)//2)**2
fc2_size=64
# Define model
class ConvNet(nn.Module):
    def __init__(self):
        super(ConvNet, self).__init__()
        # 11x11
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size= convolution_kernel_size)    
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)                      
        self.fc1 = nn.Linear(fc1_size, fc2_size)
        self.fc2 = nn.Linear(fc2_size, 10)
        

        
    def forward(self, x):
        # first conv
        x = self.pool(F.relu(self.conv1(x)))
        # flatten all dimensions except batch
        x = torch.flatten(x, 1)
        # fully connected layers
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        # print(np.amax(x.cpu().numpy()))
        

        return x

model = ConvNet().to(device)
print(model)
loss_fn = nn.CrossEntropyLoss()

# optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
optimizer = torch.optim.Adam(model.parameters(),lr=1e-3)
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Using cuda device
ConvNet(
  (conv1): Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (fc1): Linear(in_features=25, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=10, bias=True)
)
Shape of X [N, C, H, W]: torch.Size([64, 1, 12, 12])
Shape of y: torch.Size([64]) torch.int64


In [94]:
import os
file_name = "cnn_3x3.pth"
if not (os.path.isfile(file_name)):
# if(1):
    epochs = 20
    for t in range(epochs):
        print(f"Epoch {t+1}\n-------------------------------")
        train(train_dataloader, model, loss_fn, optimizer)
        test(test_dataloader, model, loss_fn)
        torch.save(model, file_name)
    print("Done!")
else:
    #model.load_state_dict(torch.load("model.pth"))
    model = torch.load( file_name)
    test(test_dataloader, model, loss_fn)
    print("Model loaded")

Test Error: 
 Accuracy: 94.8%, Avg loss: 0.169165 

Model loaded


In [95]:

model = torch.load( file_name)
bit_range=8
for ele in model.state_dict():#turn to numpy
    model.state_dict()[ele]=model.state_dict()[ele].cpu().numpy()
#turn float to int
for layers in model.state_dict():
    try:
        (channel,num,row,col)=model.state_dict()[layers].shape
        for ch in range(channel):
            for r in range(row):
                for c in range(col):
                    num=int((model.state_dict()[layers][ch][0][r][c]+1)/2*(2**bit_range-1)-(2**(bit_range-1)-1))
                    model.state_dict()[layers][ch][0][r][c]=num
    except:
        try:
            model.state_dict()[layers].shape[1]## if parameter is 2D
            row,col=model.state_dict()[layers].shape
            for row in range(model.state_dict()[layers].shape[0]):
                for col in range(model.state_dict()[layers].shape[1]):
                    num=int((model.state_dict()[layers][row][col]+1)/2*(2**bit_range-1)-(2**(bit_range-1)-1))
                    model.state_dict()[layers][row][col]=num
        except:
            #model[layers].shape #1D
            # print(model[layers].shape[0])
            for i in range(model.state_dict()[layers].shape[0]):
                num=int((model.state_dict()[layers][i]+1)/2*(2**bit_range-1)-(2**(bit_range-1)-1))
                model.state_dict()[layers][i]=num
test(test_dataloader, model, loss_fn)

Test Error: 
 Accuracy: 93.9%, Avg loss: 272454.710888 



model = torch.load( file_name)
A=29
bit_range=8
for ele in model.state_dict():#turn to numpy
    model.state_dict()[ele]=model.state_dict()[ele].cpu().numpy()
#turn float to int
for layers in model.state_dict():
    try:
        (channel,num,row,col)=model.state_dict()[layers].shape
        for ch in range(channel):
            for r in range(row):
                for c in range(col):
                    num=int((model.state_dict()[layers][ch][0][r][c]+1)/2*(2**bit_range-1)-(2**(bit_range-1)-1))
                    num=round(num/A)*A
                    model.state_dict()[layers][ch][0][r][c]=num
    except:
        try:
            model.state_dict()[layers].shape[1]## if parameter is 2D
            row,col=model.state_dict()[layers].shape
            for row in range(model.state_dict()[layers].shape[0]):
                for col in range(model.state_dict()[layers].shape[1]):
                    num=int((model.state_dict()[layers][row][col]+1)/2*(2**bit_range-1)-(2**(bit_range-1)-1))
                    num=round(num/A)*A
                    model.state_dict()[layers][row][col]=num
        except:
            #model[layers].shape #1D
            # print(model[layers].shape[0])
            for i in range(model.state_dict()[layers].shape[0]):
                num=int((model.state_dict()[layers][i]+1)/2*(2**bit_range-1)-(2**(bit_range-1)-1))
                num=round(num/A)*A
                model.state_dict()[layers][i]=num
test(test_dataloader, model, loss_fn)

In [96]:
def mynet(times):
    for i in range(times):
        img,idx=test_data[i]
        img=int_conver(img.cpu().numpy())
        con_w=np.asarray(model.state_dict()["conv1.weight"].cpu())
        con_b=np.asarray(model.state_dict()["conv1.bias"].cpu())
        
        x=conv_sz(img,con_w,convolution_kernel_size)
        x=x+con_b
        # print(x) 
        # print("con",len(bin(int(max(x.reshape(-1))))))
        x=myRelu(x)
        x=myPool(x)
        x=x.reshape(-1)
        fc1_b=np.asarray(model.state_dict()["fc1.bias"].cpu())
        fc1_w=np.asarray(model.state_dict()["fc1.weight"].cpu())
        x=FullyConnected(x,fc1_w,fc1_b)
        x=myRelu(x)

        # print("fc1",len(bin(int(max(x)))))
        fc2_b=np.asarray(model.state_dict()["fc2.bias"].cpu())
        fc2_w=np.asarray(model.state_dict()["fc2.weight"].cpu())
        x=FullyConnected(x,fc2_w,fc2_b)


In [97]:
con_w=np.asarray(model.state_dict()["conv1.weight"].cpu())
con_b=np.asarray(model.state_dict()["conv1.bias"].cpu())
def mynet_ver2(times):
    for i in range(times):
        img,idx=test_data[i]
        img=int_conver(img.cpu().numpy())
        
        
        x=conv_sz(img,con_w,convolution_kernel_size)
        x=x+con_b
        # print(x) 
        # print("con",len(bin(int(max(x.reshape(-1))))))
        x=myRelu(x)
        x=myPool(x)
        x=x.reshape(-1)
        fc1_b=np.asarray(model.state_dict()["fc1.bias"].cpu())
        fc1_w=np.asarray(model.state_dict()["fc1.weight"].cpu())
        x=FullyConnected(x,fc1_w,fc1_b)
        x=myRelu(x)

        # print("fc1",len(bin(int(max(x)))))
        fc2_b=np.asarray(model.state_dict()["fc2.bias"].cpu())
        fc2_w=np.asarray(model.state_dict()["fc2.weight"].cpu())
        x=FullyConnected(x,fc2_w,fc2_b)


In [98]:
#Test0 verilog output
hit=0
from mycnn_lib import int_conver
for i in range(1):
    img,idx=test_data[i]
    img=int_conver(img.cpu().numpy())
    print(img.shape)
    con_w=np.asarray(model.state_dict()["conv1.weight"].cpu())
    con_b=np.asarray(model.state_dict()["conv1.bias"].cpu())
    x=conv_sz(img,con_w,convolution_kernel_size)

    print(x) 
    print(x.shape)
    x=x+con_b
    # print("con",len(bin(int(max(x.reshape(-1))))))
    x=myRelu(x)
    x=myPool(x)
    
    x=x.reshape(-1)
    fc1_b=np.asarray(model.state_dict()["fc1.bias"].cpu())
    fc1_w=np.asarray(model.state_dict()["fc1.weight"].cpu())
    x=FullyConnected(x,fc1_w,fc1_b)
    x=myRelu(x)

    # print("fc1",len(bin(int(max(x)))))
    fc2_b=np.asarray(model.state_dict()["fc2.bias"].cpu())
    fc2_w=np.asarray(model.state_dict()["fc2.weight"].cpu())
    x=FullyConnected(x,fc2_w,fc2_b)

    # print("fc2",len(bin(int(max(x)))))
#     # print("predict",x.argmax(),"label",idx)
    if(x.argmax()==idx):
        hit+=1
print("lable",idx)

(1, 12, 12)
[[6.3000e+02 2.6640e+03 3.4910e+03 3.0200e+03 1.1230e+03 1.8700e+02
  0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [6.7290e+03 2.4713e+04 3.9751e+04 4.3048e+04 3.8482e+04 3.5604e+04
  3.4027e+04 2.4522e+04 1.2918e+04 2.8050e+03]
 [6.0840e+03 2.6373e+04 4.4001e+04 4.4212e+04 4.5696e+04 5.0571e+04
  6.0542e+04 4.8053e+04 2.4486e+04 4.3660e+03]
 [4.2410e+03 1.6451e+04 2.6849e+04 3.1405e+04 3.3896e+04 4.4865e+04
  6.6493e+04 6.2806e+04 2.1431e+04 1.1300e+02]
 [7.5600e+02 2.7070e+03 5.3810e+03 8.5430e+03 1.3513e+04 4.0243e+04
  6.7224e+04 5.6927e+04 9.9180e+03 9.8700e+02]
 [0.0000e+00 0.0000e+00 0.0000e+00 4.2000e+02 1.2557e+04 4.4634e+04
  6.3841e+04 2.7338e+04 2.9300e+03 1.8800e+02]
 [0.0000e+00 0.0000e+00 0.0000e+00 6.5860e+03 3.3860e+04 6.1738e+04
  5.0841e+04 8.0530e+03 1.1240e+03 4.1000e+01]
 [0.0000e+00 0.0000e+00 1.8900e+03 2.2998e+04 5.4637e+04 6.5137e+04
  2.0717e+04 2.1140e+03 1.2300e+02 0.0000e+00]
 [0.0000e+00 0.0000e+00 1.0737e+04 4.7929e+04 7.5630e+04 4.7865e+04


In [99]:
def w_fun(input_msg,file):
    try:
        file.write(input_msg)
        print("succeed!")
        return 1
    except:
        print("Failed")
        return 0

with open('test.txt','w') as f:
    w_fun("123",f)

succeed!


In [100]:
output_node_size =(input_img_sz-convolution_kernel_size+1)**2
#############################
file_location = "verilog_tcb_winograd"
con_layer_name = "winograd_layer"
#############################
with open ("./"+file_location+"/"+con_layer_name+".v",'w') as f:
    f.write("\
module "+con_layer_name+"\n\
    #(\n\
        parameter   OUTPUT_BIT  =   19,\n\
                    OUTPUT_NODE =   "+str(output_node_size)+",\n\
                    DATA_WIDTH  =   19,\n\
                    IMG_SZ    =   "+str(input_img_sz*input_img_sz)+"\n\
)\n\
(\n\
    input   clk,\n\
    input   rst,\n\
    input   [IMG_SZ*8-1:0]   img,\n\
    input   valid,\n\
    output  reg ready,\n\
    output reg [OUTPUT_BIT*OUTPUT_NODE-1:0] layer_out\n\
);\n\
\n\
reg    signed [8-1:0]  in_buffer[0:IMG_SZ-1];\n\
integer j;\n\
\n\
always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                for(j=0;j<IMG_SZ;j=j+1)\n\
                    begin\n\
                        in_buffer[j]<=0;\n\
                    end\n\
            end\n\
        else\n\
            begin\n\
                for(j=0;j<IMG_SZ;j=j+1)\n\
                    begin\n\
                        in_buffer[j]<=img[j*8+:8];\n\
                    end\n\
            end\n\
    end\n\
\n")
    #in buffer weight wire declaration
    f.write("//wire declatation\n")
    layer_output_node_count = output_node_size
    for buffer_weight_cnt in range(layer_output_node_count):
        obj_now ="in_buffer_weight"+str(buffer_weight_cnt)
        f.write("wire signed    [DATA_WIDTH-1:0]   "+obj_now+";\n")
    #replace with winograd module
    img_len = 12 
    img_index_sample = np.arange(img_len*img_len).reshape((img_len,img_len))
    con_result_len = img_len-convolution_kernel_size+1 
    # convolution_result_index_sample = np.arange(con_result_len*con_result_len).reshape((con_result_len,con_result_len))
    four_by_four_step = 5
    f.write("\n")
    DUT_index=0
    for r in range(5):
        for c in range(5):
            img_index_sample_4x4 = img_index_sample[0+r*2:4+r*2,0+c*2:4+c*2] #4x4 input buffer index
            
            f.write("win_top DUT"+str(DUT_index)+"(\n")
            DUT_index=DUT_index+1
            f.write(".rst(rst),\n.clk(clk),\n.img({")
            for idx,in_buffer_index in enumerate(img_index_sample_4x4.reshape(-1)):
                if(idx%4==0):
                    f.write("\n")
                f.write("in_buffer["+str(in_buffer_index)+"]")
                if(idx == len(img_index_sample_4x4.reshape(-1))-1):
                    f.write("}),\n")
                else:
                    f.write(",")
            port_idx=0
            
            step=c*2+r*20
            convolution_result_index_sample=np.asarray([0,1,10,11])
            convolution_result_index_sample=step+convolution_result_index_sample
            for idx,in_buffer_wieght_index in enumerate(convolution_result_index_sample):
                f.write(".win_result_"+str(port_idx)+"(")
                port_idx+=1
                f.write("in_buffer_weight"+str(in_buffer_wieght_index)+")")
                if(idx==len(convolution_result_index_sample)-1):
                    f.write("\n);\n")
                else:
                    f.write(",\n")
            

    #convolution 
    # parameter_now=model.state_dict()["conv1.weight"].cpu().numpy()
    # parameter_now=parameter_now.reshape(-1)
    # #in buffer weight = in buffer (*) con_weight
    # img_sample = np.arange(0,input_img_sz*input_img_sz).reshape(input_img_sz,input_img_sz)
    # side_lenghth =input_img_sz-convolution_kernel_size+1
    # for col in range(side_lenghth):
    #         for row in range(side_lenghth):
    #             start_x,start_y=(col,row)
    #             member_in_sample = img_sample[start_x+0:start_x+convolution_kernel_size,start_y+0:start_y+convolution_kernel_size].reshape(-1)
    #             in_buffer_weight_index=col*side_lenghth+row #9 = side_lenghth

    #             f.write("assign in_buffer_weight"+str(in_buffer_weight_index)+"=")
    #             for i in range(convolution_kernel_size*convolution_kernel_size):
    #                 #convolution_kernel_size*convolution_kernel_size=10
    #                 convolution_weight=parameter_now[i]
    #                 img_value=member_in_sample[i]

    #                 f.write("$signed(")
    #                 name ="in_buffer["+str(img_value)+"]"
    #                 number =int(convolution_weight)
    #                 f.write(name)
    #                 f.write("*("+str(number)+")")
    #                 if(i==(convolution_kernel_size*convolution_kernel_size-1)):
    #                     f.write(")")
    #                 else:
    #                     f.write(")+")

                    #TCB converter
                    # try:
                    #     f.write(D2reg(number,name))
                    # except:
                    #     pass

                # f.write(";\n")
    #weight bias wire declaration
    parameter_now=model.state_dict()["conv1.bias"].cpu().numpy()
    parameter_now=parameter_now.reshape(-1)
    #add Bias 
    for weight_bias_cnt in range(layer_output_node_count):
        obj_now ="weight_bias"+str(weight_bias_cnt)
        f.write("wire signed    [DATA_WIDTH-1:0]   "+obj_now+";\n")
        f.write("assign "+obj_now+"= in_buffer_weight"+str(weight_bias_cnt)+"+"+str(int(parameter_now))+";\n")
    #bias relu wire declaration
    for bias_relu in range(layer_output_node_count):
        obj_now ="bias_relu"+str(bias_relu)
        f.write("wire signed    [DATA_WIDTH-1:0]   "+obj_now+";\n")
    #Relu
    for relu_cnt in range(layer_output_node_count):
        obj_now ="bias_relu"+str(relu_cnt)
        f.write("assign "+obj_now+"=(weight_bias"+str(relu_cnt)+"[DATA_WIDTH-1]==1'b1)   ?   {DATA_WIDTH{1'b0}}:weight_bias"+str(relu_cnt)+";\n")
    #Output layer 
    f.write("always@(posedge clk)\n\
    begin\n\
        if(~rst)\n\
            begin\n")
    f.write("       \
    layer_out <={")
    for out_cnt in range(layer_output_node_count-1,-1,-1):
        f.write("bias_relu"+str(out_cnt))

        if(out_cnt==0):
            pass
        else:
            f.write(",")

    f.write("};\n")
    f.write("            end\n\
        else\n\
            begin\n")
    f.write("       \
    layer_out<= {(OUTPUT_BIT*OUTPUT_NODE){1'b0}};\n")

    f.write("        end\n\
    end\n")
    # f.write("assign layer_out={\n")
    # for out_cnt in range(layer_output_node_count-1,-1,-1):
    #     f.write("bias_relu"+str(out_cnt))
    #     if(out_cnt==0):
    #         pass
    #     else:
    #         f.write(",")
    # f.write("};\n")
    f.write("always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                ready<=1'b0;\n\
            end\n\
        else\n\
            begin\n\
                ready<=valid;\n\
            end\n\
    end\n")
    f.write("endmodule")

In [101]:
2#py_out maxpool

max_layer_name = "maxpool"
with open ("./"+file_location+"/"+max_layer_name+".v",'w') as f:

    f.write("\
module "+max_layer_name+"\n\
    #(\n\
        parameter   INPUT_BIT   =   19,\n\
                    INPUT_NODE  =   "+str((input_img_sz-convolution_kernel_size+1)**2)+",\n\
                    OUTPUT_NODE =   "+str(int((input_img_sz-convolution_kernel_size+1)/2)**2)+",\n\
                    DATA_WIDTH  =   19\n\
)\n\
(\n\
    input   clk,\n\
    input   rst,\n\
    input   [INPUT_BIT*INPUT_NODE-1:0] layer_in,\n\
    input   valid,\n\
    output  reg ready,\n\
    output [INPUT_BIT*OUTPUT_NODE-1:0] layer_out\n\
);\n\
reg    signed [DATA_WIDTH-1:0]  in_buffer[0:INPUT_NODE-1];\n\
genvar j;\n\
generate\n\
for(j=0;j<INPUT_NODE;j=j+1) \n\
    begin:init_block\n\
        always@(posedge clk)\n\
            begin\n\
                if(rst)\n\
                    begin\n\
                        in_buffer[j]<=0;\n\
                    end\n\
                else\n\
                    begin\n\
                        in_buffer[j]<=layer_in[j*DATA_WIDTH+(DATA_WIDTH-1):j*DATA_WIDTH+0];\n\
                    end\n\
            end\n\
    end\n\
endgenerate\n")

    sample_buffer = np.arange(0,100).reshape((10,10))
    step=int(10/2)
    for row in range(step):
            for col in range(step):
                start_x,start_y=(row,col)
                comparison_member =sample_buffer[start_x*2+0:start_x*2+2,start_y*2+0:start_y*2+2].reshape(-1)
                comparison_phase0_object0 ="com_"+str(comparison_member[0])+"_"+str(comparison_member[1])
                comparison_phase0_object1 ="com_"+str(comparison_member[2])+"_"+str(comparison_member[3])
                out_idx = col+row*5
                comparison_phase1_object0 ="com_out"+str(out_idx)+"_"+str(comparison_member[0])+"_"+str(comparison_member[1])+"_"+str(comparison_member[2])+"_"+str(comparison_member[3])
                f.write("wire [DATA_WIDTH-1:0] "+comparison_phase0_object0+";\n")
                f.write("wire [DATA_WIDTH-1:0] "+comparison_phase0_object1+";\n")
                f.write("wire [DATA_WIDTH-1:0] "+comparison_phase1_object0+";\n")
                buffer_name0="in_buffer["+str(comparison_member[0])+"]"
                buffer_name1="in_buffer["+str(comparison_member[1])+"]"
                buffer_name2="in_buffer["+str(comparison_member[2])+"]"
                buffer_name3="in_buffer["+str(comparison_member[3])+"]"
                f.write("assign "+comparison_phase0_object0+"   =  ("+buffer_name0+">"+buffer_name1+")\
    ?   "+buffer_name0+":"+buffer_name1+";\n")
                f.write("assign "+comparison_phase0_object1+"   =  ("+buffer_name2+">"+buffer_name3+")\
    ?   "+buffer_name2+":"+buffer_name3+";\n")
                f.write("assign "+comparison_phase1_object0+"   =   ("+comparison_phase0_object0+">"+comparison_phase0_object1+")\
    ?   "+comparison_phase0_object0+":"+comparison_phase0_object1+";\n")
                square = "DATA_WIDTH*"+str(out_idx)
                f.write("assign layer_out   [DATA_WIDTH+"+square+"-1:0+"+square+"]    ="+comparison_phase1_object0+";\n")


    f.write("always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                ready<=1'b0;\n\
            end\n\
        else\n\
            begin\n\
                ready<=valid;\n\
            end\n\
    end\n")
    f.write("endmodule\n")

In [102]:
#layer0
input_img_bit_size=input_img_sz*input_img_sz

in_buffer_weight_name="in_buffer_weight"
weight_to_bias_name="weight_bias"
bias_relu_name="bias_relu"
in_buffer_weight_parameter=np.asarray(model.state_dict()["fc1.weight"].cpu().numpy())
weight_bias_parameter=np.asarray(model.state_dict()["fc1.bias"].cpu().numpy())

last_layer_bit=19
data_bit_num=27

wire_cnt=in_buffer_weight_parameter.shape[1]
output_num=in_buffer_weight_parameter.shape[0]
structure_name = "_"+str(fc1_size)+"x"+str(fc2_size)+"x10"
layer0_verilog_file_name="layer0_cnn_"+str(input_img_bit_size)+structure_name

f= open ("./"+file_location+"/"+layer0_verilog_file_name+".v",'w')
f.write("module "+layer0_verilog_file_name+"\n")

f.write("(\n")
input_bit_size = last_layer_bit*wire_cnt
f.write("\
    input clk,\n\
    input rst,\n\
    input ["+str(input_bit_size)+"-1:0] layer_in,\n\
    input valid,\n\
    output  reg ready,\n\
    output ["+str(data_bit_num)+"*"+str(output_num)+"-1:0] layer_out\n"\
)
f.write(");\n")
f.write("parameter DATA_WIDTH = "+str(data_bit_num)+";\n")
f.write("parameter INPUT_DATA_CNT   =   "+str(wire_cnt)+";\n")

f.write("reg    signed [DATA_WIDTH-1:0]  in_buffer[0:INPUT_DATA_CNT-1];\n")
f.write("genvar j;\n\
generate\n\
for(j=0;j<INPUT_DATA_CNT;j=j+1) \n\
    begin:init_block\n\
        always@(posedge clk)\n\
            begin\n\
                if(rst)\n\
                    begin\n\
                        in_buffer[j]<=0;\n\
                    end\n\
                else\n\
                    begin\n\
                        in_buffer[j]<=layer_in[j*"+str(last_layer_bit)+"+"+str(last_layer_bit-1)+":j*"+str(last_layer_bit)+"+0];\n\
                    end\n\
            end\n\
    end\n\
endgenerate\n")



for naming_idx in range(output_num): 
    f.write("wire signed  [DATA_WIDTH-1:0]   ")   
    f.write(in_buffer_weight_name+str(naming_idx)+";\n")
    f.write("assign "+in_buffer_weight_name+str(naming_idx)+"=")
    #insert constant
    for in_buf_idx in range(wire_cnt):
        name="in_buffer[" +str(in_buf_idx)+"]"
        num=int(in_buffer_weight_parameter[naming_idx][in_buf_idx])

        f.write("$signed(")
        f.write(name)
        f.write("*("+str(num)+")")
        if(in_buf_idx==(wire_cnt-1)):
            f.write(")")
        else:
            f.write(")+")
        #TCB converter
        # try:
        #     f.write(D2reg(num,name))
        # except:
        #     pass
    f.write(";\n")

#weight0 to bias0
previous_layer_name=in_buffer_weight_name
#naming wire
print("wire_cnt",wire_cnt)
for naming_idx in range(output_num): 
    f.write("wire signed [DATA_WIDTH-1:0]   ")   
    f.write(weight_to_bias_name+str(naming_idx)+";\n")
for naming_idx in range(output_num):
    f.write("assign "+weight_to_bias_name+str(naming_idx)+"=")
    f.write(previous_layer_name+str(naming_idx))
    f.write("+(")
    f.write(str(int(weight_bias_parameter[naming_idx])))

    f.write(");\n")
#bias0 to relu0
previous_layer_name=weight_to_bias_name
#naming wire
print("wire_cnt",output_num)
for naming_idx in range(output_num): 
    f.write("wire signed [DATA_WIDTH-1:0]   ")   
    f.write(bias_relu_name+str(naming_idx)+";\n")
for naming_idx in range(output_num):
    f.write("assign "+bias_relu_name+str(naming_idx)+"=(")
    f.write(previous_layer_name+str(naming_idx))
    f.write("[DATA_WIDTH-1]==1'b1)   ?   ")
    f.write("{DATA_WIDTH{1'b0}}:")
    f.write(previous_layer_name+str(naming_idx))
    f.write(";\n")


f.write("assign layer_out={")
for naming_idx in range(output_num-1,-1,-1):
    if(naming_idx==0):
        f.write(bias_relu_name+str(naming_idx))
    else:
        f.write(bias_relu_name+str(naming_idx)+",")
f.write("};\n")
f.write("always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                ready<=1'b0;\n\
            end\n\
        else\n\
            begin\n\
                ready<=valid;\n\
            end\n\
    end\n")
f.write("endmodule")
f.close()


wire_cnt 25
wire_cnt 64


In [103]:
#layer1
input_img_bit_size=input_img_sz*input_img_sz
in_buffer_weight_name="in_buffer_weight"
weight_to_bias_name="weight_bias"
bias_relu_name="bias_relu"
in_buffer_weight_parameter=np.asarray(model.state_dict()["fc2.weight"].cpu().numpy())
weight_bias_parameter=np.asarray(model.state_dict()["fc2.bias"].cpu().numpy())

wire_cnt=in_buffer_weight_parameter.shape[1]
output_num=in_buffer_weight_parameter.shape[0]

last_layer_bit =27
data_bit_num=36

layer1_verilog_file_name="layer1_cnn_"+str(input_img_bit_size)+structure_name
f= open ("./"+file_location+"/"+layer1_verilog_file_name+".v",'w')
f.write("module "+layer1_verilog_file_name+"\n")

f.write("(\n")
input_bit_size = last_layer_bit*wire_cnt
f.write("\
    input clk,\n\
    input rst,\n\
    input ["+str(input_bit_size)+"-1:0] layer_in,\n\
    input valid,\n\
    output  reg ready,\n\
    output ["+str(data_bit_num)+"*"+str(output_num)+"-1:0] layer_out\n"\
)
f.write(");\n")
f.write("parameter DATA_WIDTH = "+str(data_bit_num)+";\n")
f.write("parameter INPUT_DATA_CNT   =   "+str(wire_cnt)+";\n")

f.write("reg    signed ["+str(last_layer_bit)+"-1:0]  in_buffer[0:INPUT_DATA_CNT-1];\n")
f.write("genvar j;\n\
generate\n\
for(j=0;j<INPUT_DATA_CNT;j=j+1) \n\
    begin:init_block\n\
        always@(posedge clk)\n\
            begin\n\
                if(rst)\n\
                    begin\n\
                        in_buffer[j]<=0;\n\
                    end\n\
                else\n\
                    begin\n\
                        in_buffer[j]<=layer_in[j*"+str(last_layer_bit)+"+"+str(last_layer_bit-1)+":j*"+str(last_layer_bit)+"+0];\n\
                    end\n\
            end\n\
    end\n\
endgenerate\n")



for naming_idx in range(output_num): 
    f.write("wire signed  [DATA_WIDTH-1:0]   ")   
    f.write(in_buffer_weight_name+str(naming_idx)+";\n")
    f.write("assign "+in_buffer_weight_name+str(naming_idx)+"=")
    #insert tcb
    for in_buf_idx in range(wire_cnt):
        name="in_buffer[" +str(in_buf_idx)+"]"
        num=int(in_buffer_weight_parameter[naming_idx][in_buf_idx])

        f.write("$signed(")
        f.write(name)
        f.write("*("+str(num)+")")
        if(in_buf_idx==(wire_cnt-1)):
            f.write(")")
        else:
            f.write(")+")
        # try:
        #     f.write(D2reg(num,name))
        # except:
        #     pass
    f.write(";\n")

#weight0 to bias0
previous_layer_name=in_buffer_weight_name
#naming wire
print("wire_cnt",wire_cnt)
for naming_idx in range(output_num): 
    f.write("wire signed [DATA_WIDTH-1:0]   ")   
    f.write(weight_to_bias_name+str(naming_idx)+";\n")
for naming_idx in range(output_num):
    f.write("assign "+weight_to_bias_name+str(naming_idx)+"=")
    f.write(previous_layer_name+str(naming_idx))
    f.write("+(")
    f.write(str(int(weight_bias_parameter[naming_idx])))

    f.write(");\n")
f.write("assign layer_out={")
for naming_idx in range(output_num-1,-1,-1):
    if(naming_idx==0):
        f.write(weight_to_bias_name+str(naming_idx))
    else:
        f.write(weight_to_bias_name+str(naming_idx)+",")
f.write("};\n")
f.write("always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                ready<=1'b0;\n\
            end\n\
        else\n\
            begin\n\
                ready<=valid;\n\
            end\n\
    end\n")
f.write("endmodule")
f.close()


wire_cnt 64


In [104]:
#comparator
input_data_width =36
file_name="comparator_anybit"
with open ("./"+file_location+"/"+file_name+".v",'w') as f:
    f.write("\
module comparator\n\
(\n\
input ["+str(input_data_width)+"*10-1:0] layer_out,\n\
input rst,\n\
input clk,\n\
input valid,\n\
output  reg ready,\n\
output reg [31:0] predict\n\
);\n\
parameter DATA_WIDTH="+str(input_data_width)+";\n\
reg [DATA_WIDTH-1: 0] result [0:9];\n\
wire [4+DATA_WIDTH-1:0] com_re01,com_re23,com_re45,com_re67,com_re89;\n\
reg ready_temp;\n\
always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                ready<=1'b0;\n\
                ready_temp<=1'b0;\n\
            end\n\
        else\n\
            begin\n\
                ready_temp<=valid;\n\
                ready<=ready_temp;\n\
            end\n\
    end\n\
 \n\
assign com_re01=(result[0][DATA_WIDTH-1]^result[1][DATA_WIDTH-1]) ? \n\
                                                        ((result[0][DATA_WIDTH-1]==1'b0)   ?   {4'd0,result[0]}:{4'd1,result[1]}):\n\
                                                        ((result[0]>result[1]) ? {4'd0,result[0]}:{4'd1,result[1]});\n\
assign com_re23=(result[2][DATA_WIDTH-1]^result[3][DATA_WIDTH-1]) ? \n\
                                                        ((result[2][DATA_WIDTH-1]==1'b0)   ?   {4'd2,result[2]}:{4'd3,result[3]}):\n\
                                                        ((result[2]>result[3]) ? {4'd2,result[2]}:{4'd3,result[3]});\n\
assign com_re45=(result[4][DATA_WIDTH-1]^result[5][DATA_WIDTH-1]) ? \n\
                                                        ((result[4][DATA_WIDTH-1]==1'b0)   ?   {4'd4,result[4]}:{4'd5,result[5]}):\n\
                                                        ((result[4]>result[5]) ? {4'd4,result[4]}:{4'd5,result[5]});\n\
\n\
assign com_re67=(result[6][DATA_WIDTH-1]^result[7][DATA_WIDTH-1]) ? \n\
                                                        ((result[6][DATA_WIDTH-1]==1'b0)   ?   {4'd6,result[6]}:{4'd7,result[7]}):\n\
                                                        ((result[6]>result[7]) ? {4'd6,result[6]}:{4'd7,result[7]});\n\
assign com_re89=(result[8][DATA_WIDTH-1]^result[9][DATA_WIDTH-1]) ? \n\
                                                        ((result[8][DATA_WIDTH-1]==1'b0)   ?   {4'd8,result[8]}:{4'd9,result[9]}):\n\
                                                        ((result[8]>result[9]) ? {4'd8,result[8]}:{4'd9,result[9]});\n\
wire [4+DATA_WIDTH-1:0] com_re01_23,com_re45_67,com_re0123_4567,com_re01234567_89;\n\
assign com_re01_23=(com_re01[DATA_WIDTH-1]^com_re23[DATA_WIDTH-1])   ?\n\
                                                        ((com_re01[DATA_WIDTH-1]==1'b0)  ?   com_re01:com_re23):\n\
                                                        ((com_re01[DATA_WIDTH-1:0]>com_re23[DATA_WIDTH-1:0]) ?   com_re01:com_re23);\n\
assign com_re45_67=(com_re45[DATA_WIDTH-1]^com_re67[DATA_WIDTH-1])   ?\n\
                                                        ((com_re45[DATA_WIDTH-1]==1'b0)  ?   com_re45:com_re67):\n\
                                                        ((com_re45[DATA_WIDTH-1:0]>com_re67[DATA_WIDTH-1:0]) ?   com_re45:com_re67);\n\
assign com_re0123_4567=(com_re01_23[DATA_WIDTH-1]^com_re45_67[DATA_WIDTH-1])   ?\n\
                                                        ((com_re01_23[DATA_WIDTH-1]==1'b0)  ?   com_re01_23:com_re45_67):\n\
                                                        ((com_re01_23[DATA_WIDTH-1:0]>com_re45_67[DATA_WIDTH-1:0]) ?   com_re01_23:com_re45_67);\n\
assign com_re01234567_89=(com_re0123_4567[DATA_WIDTH-1]^com_re89[DATA_WIDTH-1])   ?\n\
                                                        ((com_re0123_4567[DATA_WIDTH-1]==1'b0)  ?   com_re0123_4567:com_re89):\n\
                                                        ((com_re0123_4567[DATA_WIDTH-1:0]>com_re89[DATA_WIDTH-1:0]) ?   com_re0123_4567:com_re89);\n")
    f.write("genvar i;\n\
    generate\n\
    for(i=0;i<10;i=i+1)\n\
        begin:init_block\n\
            always@(posedge clk )\n\
            begin\n\
                if(rst)\n\
                    begin\n\
                        result[i]<={DATA_WIDTH{1'b0}};\n")
    f.write("                end\n\
                else\n\
                    begin\n")
    f.write("                   result[i]<=layer_out[DATA_WIDTH-1+DATA_WIDTH*i:0+DATA_WIDTH*i];\n\
                    end\n\
            end//end always\n\
        end//end for\n\
    endgenerate\n\
    \n\
    always@(posedge clk)\n\
        begin\n\
            if(rst)\n\
                begin\n\
                    predict<=0;\n\
                end\n\
            else\n\
                begin\n\
                    predict <={{(32-4){1'b0}},com_re01234567_89[4+DATA_WIDTH-1:4+DATA_WIDTH-1-3]};\n\
                end\n\
        end\n\
    \n\
    \n\
    endmodule\n\
    \n\
    ")

In [105]:
#top module tor tcb cnn

file_name= "cnn_top"
layer_bit_num = [19,27,36]
#input img size 
IMG_SZ = input_img_sz*input_img_sz*8
top_module_name = "top_cnn"
with open ("./"+file_location+"/"+file_name+".v",'w') as f:
    f.write("\
module "+top_module_name+"(\n\
    input   clk,\n\
    input   rst,\n\
    output  ready,\n\
    input   valid,\n\
    input   ["+str(IMG_SZ)+"-1:0]         input_img_source,\n\
    output  [31:0]              predict_number\n\
);\n\
")  
    f.write("\
wire    ready_con_out;\n\
wire    ["+str(layer_bit_num[0])+"*100-1:0] layer_con_out;\n\
")    
    f.write("\
        "+con_layer_name+" DUT_con(\n\
        .clk(clk),\n\
        .rst(rst),\n\
        .img(input_img_source),\n\
        .layer_out(layer_con_out),\n\
        .ready(ready_con_out),\n\
        .valid(valid)\n\
);\n")
    f.write("\
wire    ready_maxpool_out;\n\
wire    ["+str(layer_bit_num[0])+"*25-1:0] layer_maxpool_out;\n\
")    
    f.write("\
        maxpool DUT_maxpool(\n\
        .clk(clk),\n\
        .rst(rst),\n\
        .layer_in(layer_con_out),\n\
        .layer_out(layer_maxpool_out),\n\
        .ready(ready_maxpool_out),\n\
        .valid(ready_con_out)\n\
);\n")
    f.write("\
wire    ready_layer0_out;\n\
wire    ["+str(layer_bit_num[1])+"*"+str(fc2_size)+"-1:0] layer_0_out;\n\
")    
    f.write("\
        "+layer0_verilog_file_name+" DUT_layer0(\n\
        .clk(clk),\n\
        .rst(rst),\n\
        .layer_in(layer_maxpool_out),\n\
        .layer_out(layer_0_out),\n\
        .ready(ready_layer0_out),\n\
        .valid(ready_maxpool_out)\n\
);\n")
    f.write("\
wire    ready_layer1_out;\n\
wire    ["+str(layer_bit_num[2])+"*10-1:0] layer_1_out;\n\
")    
    f.write("\
        "+layer1_verilog_file_name+" DUT_layer1(\n\
        .clk(clk),\n\
        .rst(rst),\n\
        .layer_in(layer_0_out),\n\
        .layer_out(layer_1_out),\n\
        .ready(ready_layer1_out),\n\
        .valid(ready_layer0_out)\n\
);\n")
    f.write("\
wire    ready_comparator_out;\n\
wire    [31:0] comparator_predict;\n\
")    
    f.write("\
        comparator DUT_comparator(\n\
        .clk(clk),\n\
        .rst(rst),\n\
        .layer_out(layer_1_out),\n\
        .predict(comparator_predict),\n\
        .ready(ready_comparator_out),\n\
        .valid(ready_layer1_out)\n\
);\n")
    f.write("assign predict_number = comparator_predict;\n")
    f.write("assign ready = ready_comparator_out;\n")
    f.write("endmodule")

    wire [31:0] tcbcnn_predict;
    tcbcnn DUT_tcbcnn(
    .clk(clk),
    .rst(rst),
    .input_img_source(in_img),
    .valid(valid),
    .ready(ready_con_out),
    .predict_number(tcbcnn_predict)
    );

In [106]:
#verilog img.mem
with open ("./py_out/img.mem","w") as f:

    for i in range(9):
        canvas=np.zeros(12*12)
        img,idx=test_data[i]
        img=int_conver(img)
        print(idx)
        img=img.reshape(-1)
        for idx_canvas,ele in enumerate(img):
            #auto fill the zero
            canvas[idx_canvas]=ele
        for e_bit in reversed(canvas):
            eight_bit="{:08b}".format(int(e_bit))
            f.write(eight_bit)
            # f.write("\n")
        f.write("\n")


7
2
1
0
4
1
4
9
5


In [107]:
#tb
testbench_name = "tb"
with open("./"+file_location+"/"+testbench_name+".v","w") as f:
    f.write("module tb(\n\
    \n\
    );\n\
    \n\
    reg [144*8-1:0] img_location [0:9];\n\
    reg clk,rst,input_valid;\n\
    reg [12*12*8-1:0] img_source;\n\
    wire output_ready;\n\
    \n\
    wire [31:0] number;\n\
    always #5 clk=~clk;\n\
    integer i;\n\
    always@(negedge clk) \n\
    begin\n\
        i=i+1;\n\
        img_source = img_location[i];\n\
    end\n\
    "+top_module_name+" DUT_top(\n\
                    .clk(clk),\n\
                    .rst(rst),\n\
                    .ready(output_ready),\n\
                    .valid(input_valid),\n\
                    .input_img_source(img_source),\n\
                    .predict_number(number)\n\
                );\n\
        \n\
        initial\n\
        begin\n\
            $readmemb(\"img.mem\",img_location);\n\
        end \n\
    initial\n\
    begin\n\
        $monitor(\"number is %d\",number);\n\
        i=0;\n\
        clk=1'b0;\n\
        rst=1'b1;\n\
        input_valid=1'b1;\n\
        img_source = {(12*12*8){1'b0}};\n\
        #10 rst=1'b0; i=0;\n\
        \n\
        #200 $finish;\n\
    end\n\
    endmodule")

2D formula <br>
$Y = A^T[(GgG^T)\odot(B^TdB)]A$ <br>

In [108]:
#winograd convolution in python 
import winograd_lib
def win_fun(img_port,filter_port):
    AT=np.asarray([[1,1,1,0],[0,1,-1,1]]) #output transform
    filter_transform =winograd_lib.GgGT(filter_port)
    input_transform = winograd_lib.BTdB(img_port)
    #In verilog, img_buffer is 8bit
    #it might go wrong when execute sign extension
    in_bit = 10
    # print(input_transform)
    for ele in input_transform.reshape(-1):
        if(ele>2**(in_bit-1)):
            print("wrong ",ele)
    mul_result =filter_transform*input_transform
    output_transform = np.matmul(np.matmul(AT,mul_result),AT.T)
    return output_transform


In [109]:
iii=np.arange(0,16).reshape((4,4))
con_w
win_fun(iii,con_w)

array([[[[ 7644.,  8853.],
         [12480., 13689.]]]])

In [110]:
def win_layer(x):
    #winograd layer for test 12*12 => 10*10
    x=x.reshape((12,12))
    func_winograd_layer_output = np.zeros((img_len-3+1,img_len-3+1)).reshape(-1)
    for r in range(5):
        for c in range(5):
            winograd_4x4 =x[0+r*2:4+r*2,0+c*2:4+c*2] #4x4 input buffer index
            win_2x2 =win_fun(winograd_4x4,con_w)
            step=c*2+r*20
            t=np.asarray([0,1,10,11])
            t=t+step
            for idx in range(4):
                win_out_idx =t[idx]
                num=win_2x2.reshape(-1)[idx]
                func_winograd_layer_output[win_out_idx] =num
            # print(t)
            
    return func_winograd_layer_output.reshape((img_len-3+1,img_len-3+1))

In [121]:
#Test0 winograd verilog output
hit=0
from mycnn_lib import int_conver
for i in range(1):
    i=1
    img,idx=test_data[i]
    img=int_conver(img.cpu().numpy())
    con_w=np.asarray(model.state_dict()["conv1.weight"].cpu())
    con_b=np.asarray(model.state_dict()["conv1.bias"].cpu())
    # x=conv_sz(img,con_w,convolution_kernel_size)
    x=win_layer(img)
    x=x+con_b
    # print("con",len(bin(int(max(x.reshape(-1))))))
    x=myRelu(x)
    x=myPool(x)
    print(x)
    # t=x.reshape(-1)
    # for index,ele in enumerate(t):
    #     print(int(ele),end="")
    #     print(" ",end="")
    #     if(index%10==9):
    #         print("")
    ##<- Verilog    x[1]    3488    x[6]    28909
    ##<- Python     x[1]    43048   x[6]    44212
    
    x=x.reshape(-1)
    fc1_b=np.asarray(model.state_dict()["fc1.bias"].cpu())
    fc1_w=np.asarray(model.state_dict()["fc1.weight"].cpu())
    x=FullyConnected(x,fc1_w,fc1_b)
    x=myRelu(x)

    # print("fc1",len(bin(int(max(x)))))
    fc2_b=np.asarray(model.state_dict()["fc2.bias"].cpu())
    fc2_w=np.asarray(model.state_dict()["fc2.weight"].cpu())
    x=FullyConnected(x,fc2_w,fc2_b)

    # print("fc2",len(bin(int(max(x)))))
#     # print("predict",x.argmax(),"label",idx)
    if(x.argmax()==idx):
        hit+=1
print("lable",idx)

[[17968. 67436. 79381. 43166.     0.]
 [12688. 43640. 85983. 39941.     0.]
 [10871. 82718. 81388.  5080.  1591.]
 [21967. 93570. 76945. 66139. 59060.]
 [12095. 54748. 53779. 43551. 34720.]]
lable 2


In [118]:
img

array([[[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   0.,   7.,  51.,  77.,  74.,  20.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   2.,  58.,  98.,  63.,  95.,  58.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   2.,  38.,  24.,  14.,  96.,  49.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   0.,   1.,   4.,  62.,  97.,  18.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   0.,   0.,  34., 103.,  39.,   1.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   0.,   7.,  86.,  75.,   6.,   0.,   0.,   0.,
           0.,   0.],
        [  0.,   0.,   0.,  47., 103.,  25.,   1.,   0.,   1.,   3.,
           4.,   1.],
        [  0.,   0.,   0.,  69., 108.,  61.,  56.,  43.,  57.,  73.,
          73.,  27.],
        [  0.,   0.,   0.,  31.,  76.,  84., 100.,  83.,  70.,  53.,
          36.,  15.],
        [  0.,   0.,   0.,   1.,   4.,   5.,   7.,   5.,   3.,   0.,
           0.,   0.],

In [112]:
for i in range(1):
    img,idx=test_data[i]
    img=int_conver(img.cpu().numpy())
    con_w=np.asarray(model.state_dict()["conv1.weight"].cpu())
    
    x=win_layer(img)
    x=np.asarray(x.reshape(-1))
    for idx,ele in enumerate(x):
        # print('{:2f}'.format(ele),end="")
        print(int(ele),end="")
        print(" ",end="")
        if(idx%10 ==9):
            print()

630 2664 3491 3020 1123 187 0 0 0 0 
6729 24713 39751 43048 38482 35604 34027 24522 12918 2805 
6084 26373 44001 44212 45696 50571 60542 48053 24486 4366 
4241 16451 26849 31405 33896 44865 66493 62806 21431 113 
756 2707 5381 8543 13513 40243 67224 56927 9918 987 
0 0 0 420 12557 44634 63841 27338 2930 188 
0 0 0 6586 33860 61738 50841 8053 1124 41 
0 0 1890 22998 54637 65137 20717 2114 123 0 
0 0 10737 47929 75630 47865 8184 827 0 0 
0 0 15807 55654 63180 19847 1910 82 0 0 


In [113]:
img_part=img.reshape((12,12))
r,c=0,2
img_port=img_part[0+r*2:4+r*2,0+c*2:4+c*2]

AT=np.asarray([[1,1,1,0],[0,1,-1,1]]) #output transform
filter_transform =winograd_lib.GgGT(con_w)
input_transform = winograd_lib.BTdB(img_port)
print(input_transform)
mul_result =filter_transform*input_transform
output_transform = np.matmul(np.matmul(AT,mul_result),AT.T)
#<- Error 
#   python  155
#   verilog -101

[[ -5.  -1.   1.   1.]
 [  5.   1.  -1.  -1.]
 [  5.   1.  -1.  -1.]
 [ 14. 123.  -1.  -2.]]


In [114]:
int(np.binary_repr(-203,9),2)

309

In [115]:
filter_transform

array([[[[ 41.  , 129.  ,  20.  , 108.  ],
         [ 85.  , 302.25,  13.25, 230.5 ],
         [143.  , 119.25, 111.25,  87.5 ],
         [187.  , 292.5 , 104.5 , 210.  ]]]])

In [116]:
from sympy import MatrixSymbol, MatMul
from sympy.matrices import Matrix

winograd_unit_name = "win_top"
with open("./"+file_location+"/"+winograd_unit_name+".v","w") as f:
    f.write("\
module win_top#(\n\
    parameter   DATA_WIDTH  =   19\n\
)(\n\
    input   [4*4*8-1:0] img,\n\
    input   rst,\n\
    input   clk,\n\
    output  reg signed[DATA_WIDTH-1:0]      win_result_0,\n\
        output  reg signed[DATA_WIDTH-1:0]      win_result_1,\n\
        output  reg signed[DATA_WIDTH-1:0]      win_result_2,\n\
        output  reg signed[DATA_WIDTH-1:0]      win_result_3\n\
    );\n ")
    f.write("reg signed[9:0]   img_ff  [0:4*4-1];\n\
integer i;\n\
always@(posedge clk)\n\
    begin\n\
        if(rst)\n\
            begin\n\
                for(i=0;i<16;i=i+1)\n\
                begin\n\
                    img_ff[i] <=0;\n\
                end\n\
            end\n\
        else\n\
            begin \n\
                for(i=0;i<16;i=i+1)\n\
                begin\n\
                    img_ff[15-i] <= img[i*8+:8];  \n\
                end  \n\
            end\n\
    end //end always\n\
reg signed [DATA_WIDTH-1:0]   input_transform  [0:4*4-1];\n\
reg signed [DATA_WIDTH-1:0]   MUL  [0:4*4-1];\n\
reg signed [DATA_WIDTH-1:0]   output_transform  [0:3];\n")

    D = MatrixSymbol('input', 4, 4)
    BT= Matrix([[1,0,-1,0],[0,1,1,0],[0,-1,1,0],[0,-1,0,1]])
    AT=np.asarray([[1,1,1,0],[0,1,-1,1]]) #output transform
    G=np.asarray([[1,0,0],[0.5,0.5,0.5],[0.5,-0.5,0.5],[0,0,1]])
    input_trans_0=MatMul(BT,D)
    input_trans_1=MatMul(input_trans_0,BT.transpose())
    in_str =input_trans_1.as_explicit()

    now=0
    f.write("always@(*)\nbegin\n")
    for ele in in_str:    
        f.write("input_transform["+str(now)+"] = $signed(")
        now+=1
        str_obj=str(ele)
        #Find index of operator from str        
        symbol_index_list=[]
        input_index_list=[]
        for operator in "+-":
            symol_index=0
            while(symol_index<len(str_obj)):
                symol_index=str_obj.find(operator,symol_index)
                if(symol_index==-1):
                    break
                symbol_index_list.append(symol_index)
                symol_index+=1
        symbol_index_list.sort()
        
        # Find index of input element from str
        index=0
        while(index<len(str_obj)):
            index=str_obj.find(',',index)
            if(index==-1):
                break
            r,c=int(str_obj[index-1]),int(str_obj[index+2])
            # f.write(str(r*4+c))
            input_index_list.append(str(r*4+c))
            index+=1

        # Wrtie input txt file
        if(len(symbol_index_list)==3):
            for i in range(4):
                f.write("img_ff[")
                f.write(str(input_index_list[i]))
                f.write("]")
                try:
                    f.write(str(str_obj[symbol_index_list[i]]))
                except:
                    pass       
        else:
            f.write(str(str_obj[symbol_index_list[0]]))
            for i in range(4):
                f.write("img_ff[")
                f.write(str(input_index_list[i]))
                f.write("]")
                try:
                    f.write(str(str_obj[symbol_index_list[i+1]]))
                except:
                    pass
        f.write(");\n")
    f.write("\n")
    #MUL
    Gg=np.matmul(G,con_w.reshape((3,3)))
    Gg_GT=np.matmul(Gg,G.T)

    for idx,ele in enumerate(Gg_GT.reshape(-1)):
        num=ele
        name="input_transform["+str(idx)+"]"
        f.write("MUL["+str(idx)+"]=")
        if(".5" in str(ele)):
            ele=ele*2
            f.write("(0")
            f.write(D2reg(ele,name))
            f.write(")>>>1")
        elif(".25" in str(ele)):
            ele=ele*4
            f.write("(0")
            f.write(D2reg(ele,name))
            f.write(")>>>2")
        else:
            f.write("0")
            f.write(D2reg(ele,name))
        f.write(";\n")
    #OUTPUT TRANSFORM
    output_trans_AT=Matrix(AT)
    MUL = MatrixSymbol('MUL', 4, 4)
    output_trans_0=MatMul(output_trans_AT,MUL)
    output_trans_1=MatMul(output_trans_0,output_trans_AT.transpose())

    
    in_str =output_trans_1.as_explicit()
    now=0
    for ele in in_str:    
        f.write("output_transform["+str(now)+"] = $signed(")
        now+=1
        str_obj=str(ele)
        #Find index of operator from str        
        symbol_index_list=[]
        input_index_list=[]
        for operator in "+-":
            symol_index=0
            while(symol_index<len(str_obj)):
                symol_index=str_obj.find(operator,symol_index)
                if(symol_index==-1):
                    break
                symbol_index_list.append(symol_index)
                symol_index+=1
        symbol_index_list.sort()
        
        # Find index of input element from str
        index=0
        while(index<len(str_obj)):
            index=str_obj.find(',',index)
            if(index==-1):
                break
            r,c=int(str_obj[index-1]),int(str_obj[index+2])
            # f.write(str(r*4+c))
            input_index_list.append(str(r*4+c))
            index+=1

        # Wrtie input txt file


        for i in range(9):
            f.write("MUL[")
            f.write(str(input_index_list[i]))
            f.write("]")
            try:
                f.write(str(str_obj[symbol_index_list[i]]))
            except:
                pass       
    
        f.write(");\n")
    f.write("end\n")
    f.write("\
always@(posedge clk)\n\
begin\n\
    if(rst) \n\
    begin\n\
        win_result_0<=0;\n\
        win_result_1<=0;\n\
        win_result_2<=0;\n\
        win_result_3<=0;\n\
    end\n\
    else\n\
    begin\n\
        win_result_0<=output_transform[0];\n\
        win_result_1<=output_transform[1];\n\
        win_result_2<=output_transform[2];\n\
        win_result_3<=output_transform[3];\n\
    end\n\
end\n")
    f.write("endmodule")
